# Generated by Django 5.0.7 on 2024-07-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightroom', '0002_alter_member_options_alter_member_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='barbell_cleaned',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='bench_cleaned',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='damage_report',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='dumbbells_cleaned',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='emergency_exit_checked',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='lights_off',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='plates_cleaned',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='situp_board_cleaned',
        ),
        migrations.AddField(
            model_name='checklist',
            name='덤벨_청소',
            field=models.CharField(choices=[('예', '예'), ('아니오', '아니오')], default='아니오', max_length=3),
        ),
        migrations.AddField(
            model_name='checklist',
            name='덤벨_파손',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='바벨_청소',
            field=models.CharField(choices=[('예', '예'), ('아니오', '아니오')], default='아니오', max_length=3),
        ),
        migrations.AddField(
            model_name='checklist',
            name='바벨_파손',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='벤치_청소',
            field=models.CharField(choices=[('예', '예'), ('아니오', '아니오')], default='아니오', max_length=3),
        ),
        migrations.AddField(
            model_name='checklist',
            name='벤치_파손',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='비상문_파손',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='비상문_확인',
            field=models.CharField(choices=[('예', '예'), ('아니오', '아니오')], default='아니오', max_length=3),
        ),
        migrations.AddField(
            model_name='checklist',
            name='소등',
            field=models.CharField(choices=[('예', '예'), ('아니오', '아니오')], default='아니오', max_length=3),
        ),
        migrations.AddField(
            model_name='checklist',
            name='싯업보드_청소',
            field=models.CharField(choices=[('예', '예'), ('아니오', '아니오')], default='아니오', max_length=3),
        ),
        migrations.AddField(
            model_name='checklist',
            name='싯업보드_파손',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='요구_및_불편사항',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='원판_청소',
            field=models.CharField(choices=[('예', '예'), ('아니오', '아니오')], default='아니오', max_length=3),
        ),
        migrations.AddField(
            model_name='checklist',
            name='원판_파손',
            field=models.BooleanField(default=False),
        ),
    ]
