# Generated by Django 5.0.7 on 2024-07-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightroom', '0003_remove_checklist_barbell_cleaned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='소등_파손',
            field=models.BooleanField(default=False),
        ),
    ]
