# Generated by Django 5.0.7 on 2024-07-28 13:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightroom', '0004_checklist_소등_파손'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='checklist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checklist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
