# Generated by Django 5.0.7 on 2024-07-28 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightroom', '0005_alter_checklist_options_checklist_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='usage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
